### PR TITLE
Fix bug

### LINKED ISSUE #10: `get_entity()` incorrectly returns duplicated rows for some entities
This appers to be because entities can have multiple  postal addresses. 

```r
> get_entity('989668137')

  organisasjonsnummer             navn organisasjonsform_kode organisasjonsform_beskrivelse
1           989668137 RINGNES NORGE AS                     AS                  Aksjeselskap
2           989668137 RINGNES NORGE AS                     AS                  Aksjeselskap
                 forretningsadresse kommune              postadresse internettadresse antall_ansatte registeringsdato
1 Thorvald Meyers gate 2, 0555 OSLO    OSLO Postboks 7152, 0307 OSLO               NA              0       2006-03-31
2 Thorvald Meyers gate 2, 0555 OSLO    OSLO     Majorstua, 0307 OSLO               NA              0       2006-03-31
  naeringskode_kode naeringskode_beskrivelse sektorkode_kode     sektorkode_beskrivelse registrert_mvaregisteret
1            11.050         Produksjon av øl            2100 Private aksjeselskaper mv.                     TRUE
2            11.050         Produksjon av øl            2100 Private aksjeselskaper mv.                     TRUE
  registrert_foretaksregisteret registrert_stiftelsesregisteret registrert_frivillinghetsregisteret overordnet_enhet
1                          TRUE                           FALSE                               FALSE               NA
2                          TRUE                           FALSE                               FALSE               NA
  konkurs under_avvikling
1   FALSE           FALSE
2   FALSE           FALSE
```

### PR DESCRIPTION
**Pull request by Aeilert**
Fixes #10

### CODE REVIEW

File: R/brreg-utils.R [hunk 1]
```diff
@@ -67,7 +67,7 @@ parse_brreg_entity_single <- function(p) {
       p$forretningsadresse$postnummer, p$forretningsadresse$poststed)),
     kommune = null2na(p$forretningsadresse$kommune),
     postadresse = null2na(sprintf(
-      '%s, %s %s', unlist(p$postadresse$adresse),
+      '%s, %s %s', unlist(paste0(p$postadresse$adresse, collapse = '; ')),
```
Comment (ohjakobsen) [inline R/brreg-utils.R:70]: Documentation of the function should be expanded with the following under details: "`get_entity()` will return a single row for each entity. If one or more columns return multiple values, the values will be separated with a semicolon `;`."

**Review by ohjakobsen — APPROVED** [review]
